# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
version: 2
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
builds:
- id: git-credential-github-apps
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  goarm:
    - "6"
  goamd64:
    - "v2"
  main: main.go
- id: ghawrap
  binary: ghawrap
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  goarm:
    - "6"
  goamd64:
    - "v2"
  main: cmd/ghawrap/main.go
archives:
- id: git-credential-github-apps
  builds:
  - git-credential-github-apps
  name_template: '{{.Binary}}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
- id: ghawrap
  builds:
  - ghawrap
  name_template: '{{.Binary}}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: windows
      format: zip
    - goos: darwin
      format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
